### ISSUE TITLE
What problem does this feature solve?

### ISSUE THREAD

**Issue by WayUltimaMilha** [themeselection/materio-vuetify-vuejs-laravel-admin-template-free#5]
### What problem does this feature solve?

Please, I have a question, I realized that the requests are a mock, how could I disable this mock and be able to test triggering the real requests?

### What does the proposed solution look like?

how could i disable mock and test on real requests?

**Comment by DeepKumbhare85** [comment]
Dear @WayUltimaMilha,

Thank you for choosing our free template. We are glad to hear that you find it useful.

Regarding your query on mocking API calls, we have utilized the popular library [axios-mock-adapter](https://github.com/ctimmerm/axios-mock-adapter) to create a mock API for our template. This makes it API-ready and simplifies communication with the backend.

However, if you have real APIs to work with, you can easily remove the fake-db from the template by following the steps below:

1) Remove the @fake-db folder from the src directory.
2) Remove the import of fake-db from the main.js or main.ts file:
```
// main.ts or main.js

- import '@/@fake-db/db'
```
3) Lastly, since we no longer need axios-mock-adapter in our package, remove it from package.json:
```
{
  dependencies: {
-    "axios-mock-adapter": "^1.21.2",
  }
}
```
After completing these steps, you can replace all the fake-db API endpoints with your real API endpoints. This will remove fake-db completely from your package, and your template will now be working with real APIs.

We hope this information is helpful. If you have any further questions or concerns, please feel free to reach out to us.

~ Best Regards

**Comment by DeepKumbhare85** [comment]
Hello @WayUltimaMilha ,

Sorry for the misunderstanding,
It seems you are using the free version of the template and we don't provide any fake-db or axios-mock-adapter in free version, so all API calls are real and you can test it without removing anything.

If you are using our premium version, please raise your issue at premium repository.

I hope it helps.

~Best Regards

**Comment by WayUltimaMilha** [comment]
Good morning, thank you for contacting me, I will test the explanation to remove the mock, I would like to ask for the premium version link, thank you

**Comment by DeepKumbhare85** [comment]
Hello @WayUltimaMilha , 

If you have purchased our premium version, you can fill out this [form](https://tools.themeselection.com/github/github-access) to access the premium repository. 

If you still haven't purchased the premium version, you can purchase it here: https://themeselection.com/item/materio-vuetify-vuejs-laravel-admin-template/ 

~Regards

**Comment by WayUltimaMilha** [comment]
Thank you, I managed to access the premium version
